export interface BrennanStatus {
    playing: number;                // 1,
    source: string;                 // "Hard Disk",
    btube: boolean;                 // false,
    forceWebRefresh: boolean;       // false,
    track: string;                  // "Wouldn't Be So Bad",
    album: string;                  // "Lonely Runs Both Ways",
    artist: string;                 // "Alison Krauss",
    trackid: string;                // "2002414",
    albumid: string;                // "1000186",
    artistid: string;               // "3000068",
    timeLeft: string;               // "4", (seconds)
    playlist: string;               // "All Music",
    cdstatus: string;               // "CD 10 tracks",
    cdloaded: boolean;              // true,
    cddbmatches: string;            // "1",
    discid: string;                 // "",
    time: string;                   // "00:16:36",
    volume: string;                 // "19",
    random: string;                 // "0",
    sorted: string;                 // "1",
    background: string;             // "Idle" or "Ripping Track 1/11 25% Speed 4.4x",
    compression: string;            // "FLAC",
    logging: string;                // "Normal",
    segue: string;                  // "Off",
    tvui: string;                   // "0",
    guest: string;                  // "0",
    guestPlaylist: string;          // "0",
    hdmi: string;                   // "0",
    vCache: string;                 // "1",
    bass: string;                   // "0",
    treble: string;                 // "0",
    vu: number[]                    // [1, 2, 1, 2, 1, 1, 2, 1, 3, 4]
}